include: package:lint/analysis_options.yaml

analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore
  exclude:
    - lib/generated/**
    - '**/*.mocks.dart'
    # messy code
    - lib/screens/flight_log/**
    - lib/screens/about/**
    - test_driver/**

linter:
  rules:
    avoid_redundant_argument_values: false
    avoid_positional_boolean_parameters: false
