include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/**
    # messy code
    - lib/screens/flight_log/**
    - lib/screens/about/**

linter:
  rules:
    avoid_redundant_argument_values: false
    avoid_positional_boolean_parameters: false
