targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/**.dart
      - test/**.dart
      - test_driver/**.dart
      - pubspec.yaml
    builders:
      pubspec_generator|pubspec_generator:
        options:
          output: lib/pubspec.yaml.g.dart
      mockito|mockBuilder:
        generate_for:
          - test/generate_mocks.dart
