#!/bin/bash
# Pushes the current source and updates the production deployment in place.
#
# Redeploying the *same* deployment id is what keeps the /exec URL stable.
# `clasp deploy` without -i would mint a new URL, leaving every installed app
# talking to the previous one.

set -euo pipefail

cd "$(dirname "$0")"

DEPLOYMENT_ID="${AIRBORNE_DEPLOYMENT_ID:-}"
if [ -z "$DEPLOYMENT_ID" ]; then
    echo "Set AIRBORNE_DEPLOYMENT_ID to the deployment to update." >&2
    echo "List the available ones with: clasp deployments" >&2
    exit 1
fi

if [ -n "$(git status --porcelain -- . 2>/dev/null)" ]; then
    echo "WARNING: server/ has uncommitted changes; the build id will not identify them." >&2
fi

BUILD_ID="$(git rev-parse --short HEAD)"
DESCRIPTION="${1:-$BUILD_ID}"

# Written into the pushed sources so that `bootstrap` can report exactly which
# commit is live. Generated, and therefore git-ignored.
cat > src/01_build.js <<EOF
/** Generated by deploy.sh — do not edit. */
BUILD_ID = '${BUILD_ID}';
EOF

echo "==> Running tests"
node --test 'test/*.test.js'

echo "==> Pushing sources"
npx clasp push --force

echo "==> Updating deployment ${DEPLOYMENT_ID}"
npx clasp deploy -i "${DEPLOYMENT_ID}" -d "${DESCRIPTION}"

echo "==> Live build is ${BUILD_ID}"
