/**
 * Loads the Apps Script sources the way Apps Script loads them.
 *
 * Up there the files share one flat namespace: `60_actions.js` simply says
 * `ERROR` and finds what `10_protocol.js` declared. Node gives each file its own
 * module scope instead, so the sources would not see each other at all.
 *
 * The fix is to rebuild that flat namespace: each source ends with a guarded
 * `module.exports` listing its top-level declarations, and this loader copies
 * them onto `globalThis` in the order clasp pushes them. An undeclared
 * identifier resolves along the scope chain up to the global object, so from
 * that point on the sources reference each other exactly as they do in
 * production — no sandbox, no source rewriting, and stack traces that still
 * point at the real file and line.
 *
 * Load order therefore matters, and it comes from `.clasp.json` so that there is
 * a single place where it is written down.
 */

const fs = require('node:fs');
const path = require('node:path');

const SERVER_DIR = path.join(__dirname, '..');

/** The sources, in push order, as absolute paths. */
function sourceFiles() {
    const clasp = JSON.parse(fs.readFileSync(path.join(SERVER_DIR, '.clasp.json'), 'utf8'));
    return clasp.filePushOrder
        .map(function (relative) { return path.join(SERVER_DIR, relative); })
        // 01_build.js is generated by deploy.sh and absent from a fresh checkout.
        .filter(fs.existsSync);
}

for (const file of sourceFiles()) {
    Object.assign(globalThis, require(file));
}

module.exports = {sourceFiles: sourceFiles};
