# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_travis

default_platform(:ios)

IPA_OUTPUT_DIRECTORY = "../build/ios/ipa"
IPA_OUTPUT_NAME = "airborne.ipa"

platform :ios do
  private_lane :appstore_api_key do
    app_store_connect_api_key(
        key_id: "W5LZR27YRG",
        issuer_id: "e078f710-8cef-4b37-a9b4-67b1550dd0e5",
        key_filepath: "./fastlane/AuthKey.p8",
        #duration: 1200, # optional (maximum 1200)
        in_house: false
    )
  end

  desc "Build a signed release for the App Store"
  lane :build_production do
    appstore_api_key
    sync_code_signing(
        type: "appstore",
        git_url: "https://github.com/daniele-athome/airborne-deploy.git",
        git_basic_authorization: ENV["MATCH_GIT_AUTHORIZATION"],
        # https://github.com/fastlane/fastlane/issues/21956#issuecomment-2427256837
        # https://github.com/fastlane/fastlane/issues/29431
        force_legacy_encryption: true,
    )
    build_app(
        scheme: "Runner",
        output_directory: IPA_OUTPUT_DIRECTORY,
        output_name: IPA_OUTPUT_NAME,
    )
  end

  desc "Push a release build previously made by build_production to the App Store"
  lane :deploy_production do
    appstore_api_key
    upload_to_app_store(
        ipa: File.join(IPA_OUTPUT_DIRECTORY, IPA_OUTPUT_NAME),
        force: true,
        submit_for_review: true,
        submission_information: {
           add_id_info_uses_idfa: false,
        },
        precheck_include_in_app_purchases: false,
        automatic_release: true,
        #skip_binary_upload: true,
        skip_app_version_update: false,
        skip_metadata: false,
        skip_screenshots: false,
        overwrite_screenshots: true
    )
  end

  desc "Build and push a new release build to the App Store"
  lane :build_and_deploy_production do
    build_production
    deploy_production
  end
end
