# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    #build_app(scheme: "Runner")
    app_store_connect_api_key(
        key_id: "W5LZR27YRG",
        issuer_id: "e078f710-8cef-4b37-a9b4-67b1550dd0e5",
        key_filepath: "./fastlane/AuthKey_W5LZR27YRG.p8",
        #duration: 1200, # optional (maximum 1200)
        in_house: false
    )
    upload_to_app_store(
        submit_for_review: true,
        submission_information: {
           add_id_info_uses_idfa: false,
        },
        precheck_include_in_app_purchases: false,
        automatic_release: true,
        #skip_binary_upload: true,
        skip_app_version_update: false,
        skip_metadata: false,
        # TODO screenshots
        skip_screenshots: true
    )
  end
end
