// Mocks generated by Mockito 5.0.15 from annotations
// in airborne/test/screens/aircraft_select/aircraft_data_screen_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:airborne/helpers/aircraft_data.dart' as _i5;
import 'package:airborne/helpers/config.dart' as _i4;
import 'package:flutter/widgets.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:timezone/standalone.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeLocation_0 extends _i1.Fake implements _i2.Location {}

class _FakeImageProvider_1<T extends Object> extends _i1.Fake
    implements _i3.ImageProvider<T> {}

class _FakeType_2 extends _i1.Fake implements Type {}

/// A class which mocks [AppConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppConfig extends _i1.Mock implements _i4.AppConfig {
  MockAppConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get admin =>
      (super.noSuchMethod(Invocation.getter(#admin), returnValue: false)
          as bool);
  @override
  String get googleServiceAccountJson =>
      (super.noSuchMethod(Invocation.getter(#googleServiceAccountJson),
          returnValue: '') as String);
  @override
  String get googleApiKey =>
      (super.noSuchMethod(Invocation.getter(#googleApiKey), returnValue: '')
          as String);
  @override
  String get googleCalendarId =>
      (super.noSuchMethod(Invocation.getter(#googleCalendarId), returnValue: '')
          as String);
  @override
  double get locationLatitude => (super
          .noSuchMethod(Invocation.getter(#locationLatitude), returnValue: 0.0)
      as double);
  @override
  double get locationLongitude => (super
          .noSuchMethod(Invocation.getter(#locationLongitude), returnValue: 0.0)
      as double);
  @override
  _i2.Location get locationTimeZone =>
      (super.noSuchMethod(Invocation.getter(#locationTimeZone),
          returnValue: _FakeLocation_0()) as _i2.Location);
  @override
  List<String> get pilotNames => (super
          .noSuchMethod(Invocation.getter(#pilotNames), returnValue: <String>[])
      as List<String>);
  @override
  set currentAircraft(_i5.AircraftData? data) =>
      super.noSuchMethod(Invocation.setter(#currentAircraft, data),
          returnValueForMissingStub: null);
  @override
  List<_i5.AircraftData> get aircrafts =>
      (super.noSuchMethod(Invocation.getter(#aircrafts),
          returnValue: <_i5.AircraftData>[]) as List<_i5.AircraftData>);
  @override
  set pilotName(String? value) =>
      super.noSuchMethod(Invocation.setter(#pilotName, value),
          returnValueForMissingStub: null);
  @override
  _i6.Future<void> init() => (super.noSuchMethod(Invocation.method(#init, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i3.ImageProvider<Object> getPilotAvatar(String? name) =>
      (super.noSuchMethod(Invocation.method(#getPilotAvatar, [name]),
              returnValue: _FakeImageProvider_1<Object>())
          as _i3.ImageProvider<Object>);
  @override
  void addAircraft(_i5.AircraftData? data) =>
      super.noSuchMethod(Invocation.method(#addAircraft, [data]),
          returnValueForMissingStub: null);
  @override
  void updateAircraft(_i5.AircraftData? data) =>
      super.noSuchMethod(Invocation.method(#updateAircraft, [data]),
          returnValueForMissingStub: null);
  @override
  void removeAircraft(String? id) =>
      super.noSuchMethod(Invocation.method(#removeAircraft, [id]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LocalizationsDelegate].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalizationsDelegate<T> extends _i1.Mock
    implements _i3.LocalizationsDelegate<T> {
  MockLocalizationsDelegate() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Type get type =>
      (super.noSuchMethod(Invocation.getter(#type), returnValue: _FakeType_2())
          as Type);
  @override
  bool isSupported(_i7.Locale? locale) =>
      (super.noSuchMethod(Invocation.method(#isSupported, [locale]),
          returnValue: false) as bool);
  @override
  _i6.Future<T> load(_i7.Locale? locale) =>
      (super.noSuchMethod(Invocation.method(#load, [locale]),
          returnValue: Future<T>.value(null)) as _i6.Future<T>);
  @override
  bool shouldReload(_i3.LocalizationsDelegate<T>? old) =>
      (super.noSuchMethod(Invocation.method(#shouldReload, [old]),
          returnValue: false) as bool);
  @override
  String toString() => super.toString();
}
