title: Airborne
description: Aircraft Management
theme: jekyll-theme-architect
show_downloads: false
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
