title: Airborne
description: Aircraft Management
theme: architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
