# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to Google Play internal testing track"
  lane :deploy_internal do
    upload_to_play_store(
        track: 'internal',
        metadata_path: "fastlane/metadata/android",
        aab: "../build/app/outputs/bundle/release/app-release.aab")
  end

  desc "Deploy a new version to Google Play alpha testing track"
  lane :deploy_alpha do
    upload_to_play_store(
        track: 'alpha',
        metadata_path: "fastlane/metadata/android",
        aab: "../build/app/outputs/bundle/release/app-release.aab")
  end

  desc "Deploy a new version to Google Play beta testing track"
  lane :deploy_beta do
    upload_to_play_store(
        track: 'beta',
        metadata_path: "fastlane/metadata/android",
        aab: "../build/app/outputs/bundle/release/app-release.aab")
  end
end
