name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'

      - name: Install dependencies
        run: flutter pub get

      # TODO create .env?

      - name: Build Linux application
        run: |
          flutter config --enable-linux-desktop
          flutter build linux
