name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    runs-on: ubuntu-latest
    # TODO environment: ???

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'

      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev

      - name: Install dependencies
        run: |
          flutter pub get
          flutter config --enable-linux-desktop

      - name: Run tests
        run: flutter test -r expanded

      - name: Build Linux application
        run: |
          flutter build linux
