name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    runs-on: ubuntu-latest
    environment: i8104

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'

      - name: Install system libraries
        run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev

      - name: Install dependencies
        run: flutter pub get

      - name: Decrypt files
        env:
          ENCRYPTED_FILE_KEY: ${{ secrets.ENCRYPTED_FILE_KEY }}
          ENCRYPTED_FILE_IV: ${{ secrets.ENCRYPTED_FILE_IV }}
        run: |
          openssl aes-256-cbc -K $ENCRYPTED_FILE_KEY -iv $ENCRYPTED_FILE_IV -in deploy/i8104/env.txt.enc -out assets/data/.env -d
          openssl aes-256-cbc -K $ENCRYPTED_FILE_KEY -iv $ENCRYPTED_FILE_IV -in deploy/i8104/service_account.json.enc -out assets/data/service_account.json -d
          openssl aes-256-cbc -K $ENCRYPTED_FILE_KEY -iv $ENCRYPTED_FILE_IV -in deploy/i8104/aircraft.jpg.enc -out assets/data/aircraft.jpg -d
          openssl aes-256-cbc -K $ENCRYPTED_FILE_KEY -iv $ENCRYPTED_FILE_IV -in deploy/i8104/avatar-claudia.jpg.enc -out assets/data/avatar-claudia.jpg -d
          openssl aes-256-cbc -K $ENCRYPTED_FILE_KEY -iv $ENCRYPTED_FILE_IV -in deploy/i8104/avatar-daniele.jpg.enc -out assets/data/avatar-daniele.jpg -d
          openssl aes-256-cbc -K $ENCRYPTED_FILE_KEY -iv $ENCRYPTED_FILE_IV -in deploy/i8104/avatar-davide.jpg.enc -out assets/data/avatar-davide.jpg -d
          openssl aes-256-cbc -K $ENCRYPTED_FILE_KEY -iv $ENCRYPTED_FILE_IV -in deploy/i8104/avatar-manuel.jpg.enc -out assets/data/avatar-manuel.jpg -d
          openssl aes-256-cbc -K $ENCRYPTED_FILE_KEY -iv $ENCRYPTED_FILE_IV -in deploy/i8104/avatar-simone.jpg.enc -out assets/data/avatar-simone.jpg -d
          openssl aes-256-cbc -K $ENCRYPTED_FILE_KEY -iv $ENCRYPTED_FILE_IV -in deploy/i8104/avatar-victoriano.jpg.enc -out assets/data/avatar-victoriano.jpg -d

      - name: Build Linux application
        run: |
          flutter config --enable-linux-desktop
          flutter build linux
