name: screenshots

on:
  push:
  workflow_dispatch:

env:
  flutter_version: '3.35.1'

jobs:
  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locale:
          - en-US
#          - it-IT
        device:
          - Nexus 5X
#          - Nexus 6P
#          - Nexus 9
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Install tools
        run: sudo apt-get install -y imagemagick

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Building generated source code
        run: dart run build_runner build

      - name: Install screenshots tool
        # TODO get specific dependency from pubspec.yaml
        run: flutter pub global activate -sgit https://github.com/daniele-athome/screenshots.git --git-ref 6e1efc54a13e6087496a7b359887796a7d223267

      - name: Normalize device name
        run: |
          DEVICE_NAME="${{ matrix.device }}"
          echo "DEVICE_NAME=${DEVICE_NAME// /_}" >>$GITHUB_ENV

      - name: Run screenshots tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64
          profile: '${{ matrix.device }}'
          avd-name: '${{ env.DEVICE_NAME }}'
          emulator-options: '-no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -no-metrics'
          script: |
            flutter config --android-sdk /usr/local/lib/android/sdk
            flutter doctor
            flutter devices
            ~/.pub-cache/bin/screenshots -c screenshots_android.yaml

      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        with:
          name: 'android-screenshots'
          path: './android/fastlane/metadata/android/*/images/*/*.png'
