name: screenshots

on:
  push:
  workflow_dispatch:

env:
  flutter_version: '3.35.1'

jobs:
  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          - avd_name: Pixel 5
            device_name: pixel_5
#          - Nexus 6P
#          - Nexus 9
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Install tools
        run: sudo apt-get install -y imagemagick

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Building generated source code
        run: dart run build_runner build

      - name: Install screenshots tool
        # TODO get specific dependency from pubspec.yaml
        run: flutter pub global activate -sgit https://github.com/daniele-athome/screenshots.git --git-ref 4edd186f3bb0d23c8c9d10effa8b1238451171c8

#      - name: Normalize device name
#        run: |
#          DEVICE_NAME="${{ matrix.device }}"
#          echo "DEVICE_NAME=${DEVICE_NAME// /_}" >>$GITHUB_ENV

      - name: Prepare screenshots tool configuration
        run: |
          cat << EOF >/tmp/screenshots.yaml
          driver: screenshots/screenshots_driver.dart
          tests:
            - screenshots/app_screenshots.dart
          
          staging: ./.screenshots
          
          locales:
            - en-US
            - it-IT
          
          devices:
            android:
              # phone
              ${{ matrix.device.device_name }}:
                orientation:
                  - Portrait
          frame: true
          EOF
          cat /tmp/screenshots.yaml 

      - name: Run screenshots tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64
          profile: '${{ matrix.device.device_name }}'
          avd-name: '${{ matrix.device.avd_name }}'
          emulator-options: '-no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -no-metrics'
          script: |
            flutter config --android-sdk /usr/local/lib/android/sdk
            flutter doctor
            flutter devices
            ~/.pub-cache/bin/screenshots -c >/tmp/screenshots.yaml

      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        with:
          name: 'android-screenshots'
          path: './android/fastlane/metadata/android/*/images/*/*.png'
