name: server

on:
  push:
    paths:
      - 'server/**'
      - '.github/workflows/server.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v6
        with:
          path: |
            .asdf/**
            vendor/bundle
          key: ${{ runner.os }}-cache-${{ hashFiles('**/cache.key') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      - name: Run tests
        run: npm run test
        working-directory: ./server
